name: 'GitHub Actions Weather Bot'

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - name: 'Get Result'
        run: bash ./weather.sh
      - name: 'Send mail'
        uses: dawidd6/action-send-mail@master
        with:
          server_address: smtp.sendgrid.net
          server_port: 465
          username: apikey
          password: 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
          subject: Shanghai Weather Report
          body: file://result.html
          to: don.ling.lok@gmail.com
          from: GitHub Actions
          content_type: text/html
